package com.mycompany.sayangwaterthemepark;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aqila
 */
public class customerForm extends javax.swing.JFrame {

    /**
     * Creates new form customerForm
     */
    public customerForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chargeBG = new javax.swing.ButtonGroup();
        couponBG = new javax.swing.ButtonGroup();
        titleLBL = new javax.swing.JLabel();
        nameLBL = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        numberTF = new javax.swing.JTextField();
        chargeLBL = new javax.swing.JLabel();
        normalRB = new javax.swing.JRadioButton();
        myKadRB = new javax.swing.JRadioButton();
        adultLBL = new javax.swing.JLabel();
        adultTF = new javax.swing.JTextField();
        childrenLBL = new javax.swing.JLabel();
        childrenTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        totalTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fiveRB = new javax.swing.JRadioButton();
        tenRB = new javax.swing.JRadioButton();
        fifteenRB = new javax.swing.JRadioButton();
        calculateBTN = new javax.swing.JButton();
        searchBTN = new javax.swing.JButton();
        displayBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTA = new javax.swing.JTextArea();
        editBTN = new javax.swing.JButton();
        deleteBTN = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();
        searchTF = new javax.swing.JTextField();
        searchLBL = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        informationTA = new javax.swing.JTextArea();
        saveBTN = new javax.swing.JButton();
        totalLbl = new javax.swing.JLabel();
        seniorTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sayang Theme Park");

        titleLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titleLBL.setText("SAYANG THEME PARK");

        nameLBL.setText("Enter Your Name : ");

        jLabel1.setText("Contact Number :");

        chargeLBL.setText("Charge Rate :");

        chargeBG.add(normalRB);
        normalRB.setText("Normal");

        chargeBG.add(myKadRB);
        myKadRB.setText("MyKad Rate");

        adultLBL.setText("Number Of Adult :");

        childrenLBL.setText("Number Of Children :");

        childrenTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                childrenTFActionPerformed(evt);
            }
        });

        jLabel2.setText("Number Of Senior Citizen:");

        totalTF.setEditable(false);

        jLabel3.setText("Coupon Promotion :");

        couponBG.add(fiveRB);
        fiveRB.setText("5%");

        couponBG.add(tenRB);
        tenRB.setText("10%");

        couponBG.add(fifteenRB);
        fifteenRB.setText("15%");
        fifteenRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fifteenRBActionPerformed(evt);
            }
        });

        calculateBTN.setText("Calculate ");
        calculateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateBTNActionPerformed(evt);
            }
        });

        searchBTN.setText("Search");
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });

        displayBTN.setText("Display All");

        displayTA.setEditable(false);
        displayTA.setColumns(20);
        displayTA.setRows(5);
        jScrollPane1.setViewportView(displayTA);

        editBTN.setText("Edit Customer Information");

        deleteBTN.setText("Delete");

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        exitBTN.setText("Exit");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        searchTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTFActionPerformed(evt);
            }
        });

        searchLBL.setText("Search Customer :");

        informationTA.setEditable(false);
        informationTA.setColumns(20);
        informationTA.setRows(5);
        jScrollPane2.setViewportView(informationTA);

        saveBTN.setText("Save Into Text File");
        saveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTNActionPerformed(evt);
            }
        });

        totalLbl.setText("Total charge :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(calculateBTN)
                                .addGap(18, 18, 18)
                                .addComponent(deleteBTN)
                                .addGap(18, 18, 18)
                                .addComponent(resetBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(exitBTN))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saveBTN)
                                .addGap(18, 18, 18)
                                .addComponent(editBTN))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(totalLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(totalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nameLBL)
                                            .addComponent(jLabel1)
                                            .addComponent(chargeLBL)
                                            .addComponent(adultLBL)
                                            .addComponent(childrenLBL)
                                            .addComponent(jLabel3))
                                        .addGap(44, 44, 44))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(fiveRB)
                                        .addGap(18, 18, 18)
                                        .addComponent(tenRB)
                                        .addGap(18, 18, 18)
                                        .addComponent(fifteenRB))
                                    .addComponent(nameTF, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numberTF, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(normalRB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                                        .addComponent(myKadRB))
                                    .addComponent(adultTF, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(childrenTF, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(seniorTF))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(searchLBL)
                                                .addComponent(displayBTN))
                                            .addComponent(searchBTN))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(titleLBL)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLBL)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLBL)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchLBL)
                    .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(numberTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(normalRB)
                            .addComponent(myKadRB)
                            .addComponent(chargeLBL))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adultLBL)
                            .addComponent(adultTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(childrenLBL)
                            .addComponent(childrenTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(displayBTN))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(seniorTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(fiveRB)
                                    .addComponent(tenRB)
                                    .addComponent(fifteenRB))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(totalLbl)
                                    .addComponent(totalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(deleteBTN)
                                    .addComponent(resetBtn)
                                    .addComponent(exitBTN)
                                    .addComponent(calculateBTN))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(saveBTN)
                                    .addComponent(editBTN))
                                .addGap(246, 246, 246))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    public int calculateAdult(int adult){
        int price = 0;
        if(normalRB.isSelected()){
            price = adult *100;
        }else if(myKadRB.isSelected()){
            price = adult * 50;
        }
        return price;
    }
         public int calculateChild(int child){
        int price = 0;
        if(normalRB.isSelected()){
            price = child *60;
        }else if(myKadRB.isSelected()){
            price = child * 30;
        }
        return price;
    }
            
         public int calculateSenior(int senior){
        int price = 0;
        if(normalRB.isSelected()){
            price = senior *30;
        }else if(myKadRB.isSelected()){
            price = senior * 15;
        }
        return price;
    }
         
         public void saveIntoTextFile(CustomerClass customer)throws IOException
         {
             File infile = new File("D:/College stuff/Sem 2/Programming 2/A231_STIA1123_Prjct1_Opal/projectFile.txt");
             FileWriter fw = new FileWriter(infile);
             PrintWriter pw = new PrintWriter(fw);
             pw.println(customer.getName());
             pw.println(customer.getNumber());
             pw.println(customer.getChargeRate());
             pw.println(customer.getNumOfAdult());
             pw.println(customer.getNumOfChildren());
             pw.println(customer.getNumOfSenior());
             pw.println(customer.getCoupon());
             pw.println(customer.getPrice());
             pw.close();
             fw.close();
         }
            
    private void calculateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateBTNActionPerformed
        // TODO add your handling code here:
        try{
        String name = nameTF.getText();
        int number = Integer.parseInt(numberTF.getText());
        String chargeRate = null;
        if(normalRB.isSelected()){
            chargeRate = "Normal Charge";
        }
        else if (myKadRB.isSelected()){
            chargeRate = "MyKad Charge";
        }
        
        int adult = Integer.parseInt(adultTF.getText());
        int adultPrice = calculateAdult(adult);
        
        int child = Integer.parseInt(childrenTF.getText());
        int childPrice = calculateChild(child);
        
        int senior = Integer.parseInt(seniorTF.getText());
        int seniorPrice = calculateSenior(senior);
        double coupon = 0.0;
        if(fiveRB.isSelected()){
            coupon = 0.05;   
        }
        else if(tenRB.isSelected()){
            coupon = 0.1;
        }else if (fifteenRB.isSelected()){
            coupon = 1.5;
        }
        double couponPrice = (adultPrice + childPrice + seniorPrice)*coupon;
        
        double totalPrice = (adultPrice + childPrice + seniorPrice)-couponPrice;
        
        totalTF.setText(String.valueOf(totalPrice));
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Wrong input bro!");
        }
    }//GEN-LAST:event_calculateBTNActionPerformed

    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBTNActionPerformed

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBTNActionPerformed

    private void fifteenRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fifteenRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fifteenRBActionPerformed

    private void childrenTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_childrenTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_childrenTFActionPerformed

    private void saveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTNActionPerformed
        // TODO add your handling code here:
        String name = nameTF.getText();
        int number = Integer.parseInt(numberTF.getText());
        String chargeRate = null;
        if(normalRB.isSelected()){
            chargeRate = "Normal Charge";
        }
        else if (myKadRB.isSelected()){
            chargeRate = "MyKad Charge";
        }
        
        int adult = Integer.parseInt(adultTF.getText());
        int adultPrice = calculateAdult(adult);
        
        int child = Integer.parseInt(childrenTF.getText());
        int childPrice = calculateChild(child);
        
        int senior = Integer.parseInt(seniorTF.getText());
        int seniorPrice = calculateSenior(senior);
        double coupon = 0;
        if(fiveRB.isSelected()){
            coupon = 0.05;   
        }
        else if(tenRB.isSelected()){
            coupon = 0.1;
        }else if (fifteenRB.isSelected()){
            coupon = 1.5;
        }
        double totalPrice = (adultPrice + childPrice + seniorPrice)*coupon;
        CustomerClass customer = new CustomerClass(name, number, chargeRate, adultPrice, childPrice, seniorPrice, coupon, totalPrice);
        try
        {
            saveIntoTextFile(customer);
        }catch(IOException ex)
        {
            JOptionPane.showMessageDialog(this, "The data have been save into text file successfully");                    
        }
    }//GEN-LAST:event_saveBTNActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        nameTF.setText("");
        numberTF.setText("");
        adultTF.setText("");
        chargeBG.clearSelection();
        childrenTF.setText("");
        seniorTF.setText("");
        couponBG.clearSelection();
        totalTF.setText("");
        searchTF.setText("");
        displayTA.setText("");
        informationTA.setText("");
        nameTF.requestFocusInWindow();
    }//GEN-LAST:event_resetBtnActionPerformed

    private void searchTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adultLBL;
    private javax.swing.JTextField adultTF;
    private javax.swing.JButton calculateBTN;
    private javax.swing.ButtonGroup chargeBG;
    private javax.swing.JLabel chargeLBL;
    private javax.swing.JLabel childrenLBL;
    private javax.swing.JTextField childrenTF;
    private javax.swing.ButtonGroup couponBG;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JButton displayBTN;
    private javax.swing.JTextArea displayTA;
    private javax.swing.JButton editBTN;
    private javax.swing.JButton exitBTN;
    private javax.swing.JRadioButton fifteenRB;
    private javax.swing.JRadioButton fiveRB;
    private javax.swing.JTextArea informationTA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton myKadRB;
    private javax.swing.JLabel nameLBL;
    private javax.swing.JTextField nameTF;
    private javax.swing.JRadioButton normalRB;
    private javax.swing.JTextField numberTF;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton saveBTN;
    private javax.swing.JButton searchBTN;
    private javax.swing.JLabel searchLBL;
    private javax.swing.JTextField searchTF;
    private javax.swing.JTextField seniorTF;
    private javax.swing.JRadioButton tenRB;
    private javax.swing.JLabel titleLBL;
    private javax.swing.JLabel totalLbl;
    private javax.swing.JTextField totalTF;
    // End of variables declaration//GEN-END:variables
}
